- hosts: all
  become: true
  pre_tasks:
  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: motd player
    copy: 
        content: "Ansible Managed by Bose\n"
        dest: /etc/motd

  - name: turn on httpd service
    service:
     name: httpd
     state: started
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
      - Prometheus
      - apache2
